# This is a basic workflow to help you get started with Actions

name: compile-you-get-stable

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0,6,12,18 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pip install --upgrade pyinstaller
          cd you-get-root && cp launcher.py stable/launcher.py
          cd stable
          ./get.sh
          pyinstaller -F launcher.py
          %CD%/dist/launcher.exe --version
          cd ../../
          mkdir -p build/you-get/stable
          mv you-get-root/stable/dist/launcher.exe build/you-get/stable/you-get.exe
                  git config --local user.email "i@focuschen.com"
          git config --local user.name "Focus Chen"
          git add -f build/you-get/stable/you-get.exe
          git commit -m "update you-get exe" --quiet
        shell: cmd
      - uses: ad-m/github-push-action@master
        with:
          branch: master #ignore if your branch is master
          github_token: ${{ secrets.GH_TOKEN }}
