# This is a basic workflow to help you get started with Actions

name: compile-ykdl stable

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
   paths:
    - '.github/workflows/*yml'
  schedule:
    - cron: 0 0,6,12,18 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: npm install
        run: npm install move-cli@2.0.0 -g
        
      - name: Run a multi-line script
        run: |
          git config --local user.email "i@focuschen.com"
          git config --local user.name "Focus Chen"
          pip install --upgrade pyinstaller ykdl
          cd ykdl
          python get_stable.py && %CD%/move.bat
          echo %CD%
          %CD%/unzip.bat
          echo %CD%
          curl -o build.bat https://raw.githubusercontent.com/hifocus/vdl.exe/master/ykdl/build_ykdl_actions.cmd
          %CD%/ykdl.exe -h
          move ykdl.exe ../../../
          cd ../../../
          set myDIR=build\stable\
          IF not exist %myDIR% (mkdir %myDIR%)
          move ykdl.exe %CD%\build\stable\
          cd build\stable\
          IF EXIST ykdl.exe (del ykdl.exe)
          git add * --ignore-errors
          git commit --quiet -m "update you-get exe"
        shell: cmd
      - uses: ad-m/github-push-action@master
        with:
          branch: master #ignore if your branch is master
          github_token: ${{ secrets.GH_TOKEN }}
