# This is a basic workflow to help you get started with Actions

name: compile-ykdl-stable

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
   paths:
    - '.github/workflows/compile-ykdl-stable.yml'
  schedule:
    - cron: 5 0,6,12,18 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git config --local user.email "i@focuschen.com"
          git config --local user.name "Focus Chen"
          pip install --upgrade pyinstaller
          cd ykdl
          git clone https://github.com/SeaHOH/ykdl.git .
          ren ykdl stable
          move get_stable.py stable\
          move build_ykdl_actions.cmd stable\
          cd stable
          python get_stable.py
          %CD%\checkout.bat
          %CD%\build_ykdl_actions.cmd
          %CD%\ykdl.exe -h
          cd ../../
          set myDIR=build\stable\ykdl\
          IF not exist %myDIR% (mkdir %myDIR%)
          cd build\stable\ykdl
          IF EXIST ykdl.exe (del ykdl.exe)
          cd ../../../
          move %CD%\ykdl\stable\ykdl.exe %CD%\build\stable\
          cd build\stable\
          git add . --ignore-errors -f
          git commit --quiet -m "update ykdl stable exe"
        shell: cmd
        
      - uses: ad-m/github-push-action@master
        with:
          branch: master #ignore if your branch is master
          github_token: ${{ secrets.GH_TOKEN }}
